env:
  global:
    - CC_TEST_REPORTER_ID=dd3eff2e7f99ceb7e067747055dd6a925351986cb9718a6ac70a6af101370402
language: node_js
install:
  - npm install
node_js:
  - 'stable'
dist: trusty
cache:
  directories:
    - 'node_modules'

addons:
  chrome: stable
services:
  - postgresql
postgres:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
before_script:
  - "psql -c 'create database travis_ci_test;' -U postgres < travis.sql"
  - npm i -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
